CDD-2442 Shorten feature flags and feedback api target groups name

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -16,6 +16,9 @@ jobs:
   build_base:
     name: Build base env
     runs-on: ubuntu-latest
+    outputs:
+      public_env: ${{ steps.set_env.outputs.PUBLIC_ENV }}
+      auth_env: ${{ steps.set_env.outputs.AUTH_ENV }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -31,64 +34,123 @@ jobs:
       - uses: ./.github/actions/setup-zsh
       - uses: ./.github/actions/short-sha
 
-      - name: Build base env for public & auth
+      - name: Determine Environment Names
+        id: set_env
+        run: |
+          PUBLIC_ENV="ci-${{ env.SHORT_SHA }}"
+          AUTH_ENV="ci-${{ env.SHORT_SHA }}-a"
+
+          echo "PUBLIC_ENV=${PUBLIC_ENV}" >> $GITHUB_ENV
+          echo "AUTH_ENV=${AUTH_ENV}" >> $GITHUB_ENV
+
+          echo "PUBLIC_ENV=${PUBLIC_ENV}"
+          echo "AUTH_ENV=${AUTH_ENV}"
+        shell: bash
+
+      - name: Build base env
         run: |
           source uhd.sh
           uhd terraform init:layer 20-app
-          uhd terraform apply:layer 20-app ci-$SHORT_SHA
-          uhd terraform apply:layer 20-app ci-$SHORT_SHA-a
+          uhd terraform apply:layer 20-app $PUBLIC_ENV
         shell: zsh {0}
+
+  fast_forward_env_branches:
+    name: Fast forward env branches
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    outputs:
+      deploy_auth_dev: ${{ steps.fast_forward_merge.outputs.deploy_auth_dev }}
+      deploy_auth_test: ${{ steps.fast_forward_merge.outputs.deploy_auth_test }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.base_ref }}
+
+      - uses: ./.github/actions/setup-zsh
+
+      - name: Fast forward env branches
+        id: fast_forward_merge
+        run: |
+          echo "Starting fast-forward merge..."
+          if scripts/fast-forward-env-branches.sh; then
+            echo "Fast forward merge completed successfully."
+          else
+            echo "Fast forward merge failed!" >&2
+            exit 1
+          fi
+        shell: zsh {0}
+        env:
+          CI: "true"
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   terraform_plan:
     name: Terraform plan
     runs-on: ubuntu-latest
     needs: ["build_base"]
+    strategy:
+      fail-fast: false
+      matrix:
+        environment: [ public, auth ]
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
 
-      - name: Configure AWS credentials for tools account
-        uses: ./.github/actions/configure-aws-credentials
+      - name: Set TARGET_ENV
+        run: |
+          if [[ "${{ matrix.environment }}" == "public" ]]; then
+            echo "TARGET_ENV=${{ needs.build_base.outputs.public_env }}" >> $GITHUB_ENV
+          else
+            echo "TARGET_ENV=${{ needs.build_base.outputs.auth_env }}" >> $GITHUB_ENV
+          fi
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
+          role-to-assume: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
           aws-region: ${{ env.AWS_REGION }}
-          tools-account-role: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
 
       - uses: ./.github/actions/setup-terraform
       - uses: ./.github/actions/setup-zsh
-      - uses: ./.github/actions/short-sha
 
-      - name: Terraform plan for public & auth
+      - name: Terraform plan
         run: |
           source uhd.sh
           uhd terraform init
-          uhd terraform plan:layer 20-app ci-$SHORT_SHA
-          uhd terraform plan:layer 20-app ci-$SHORT_SHA-a
+          uhd terraform plan:layer 20-app $TARGET_ENV
         shell: zsh {0}
 
   terraform_apply:
     name: Terraform apply
     runs-on: ubuntu-latest
     needs: ["terraform_plan"]
+    strategy:
+      fail-fast: false
+      matrix:
+        environment: [ public, auth ]
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
 
-      - name: Configure AWS credentials for tools account
-        uses: ./.github/actions/configure-aws-credentials
+      - name: Set TARGET_ENV
+        run: |
+          if [[ "${{ matrix.environment }}" == "public" ]]; then
+            echo "TARGET_ENV=${{ needs.build_base.outputs.public_env }}" >> $GITHUB_ENV
+          else
+            echo "TARGET_ENV=${{ needs.build_base.outputs.auth_env }}" >> $GITHUB_ENV
+          fi
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
+          role-to-assume: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
           aws-region: ${{ env.AWS_REGION }}
-          tools-account-role: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
 
       - uses: ./.github/actions/setup-terraform
       - uses: ./.github/actions/setup-zsh
-      - uses: ./.github/actions/short-sha
 
-      - name: Terraform apply for public & auth
+      - name: Terraform apply
         run: |
           source uhd.sh
-          uhd terraform init
-          uhd terraform apply:layer 20-app ci-$SHORT_SHA
-          uhd terraform apply:layer 20-app ci-$SHORT_SHA-a
+          uhd terraform apply:layer 20-app $TARGET_ENV
         shell: zsh {0}
 
   push_docker_images:
@@ -99,19 +161,18 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Configure AWS credentials
-        uses: ./.github/actions/configure-aws-credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
+          role-to-assume: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
           aws-region: ${{ env.AWS_REGION }}
-          tools-account-role: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
 
       - uses: ./.github/actions/setup-zsh
-      - uses: ./.github/actions/short-sha
 
-      - name: Pull / push docker images for public & auth
+      - name: Push Docker images
         run: |
           source uhd.sh
-          uhd docker update test ci-$SHORT_SHA
-          uhd docker update test ci-$SHORT_SHA-a
+          uhd docker update public $PUBLIC_ENV
+          uhd docker update auth $AUTH_ENV
         shell: zsh {0}
 
   restart_services:
@@ -122,76 +183,41 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Configure AWS credentials
-        uses: ./.github/actions/configure-aws-credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
+          role-to-assume: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
           aws-region: ${{ env.AWS_REGION }}
-          tools-account-role: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
 
       - uses: ./.github/actions/setup-terraform
       - uses: ./.github/actions/setup-zsh
-      - uses: ./.github/actions/short-sha
 
-      - name: Restart ECS services for public & auth
+      - name: Restart services
         run: |
           source uhd.sh
-          uhd ecs restart-services ci-$SHORT_SHA
-          uhd ecs restart-services ci-$SHORT_SHA-a
-        shell: zsh {0}
-
-      - name: Redeploy lambda functions for public & auth
-        run: |
-          source uhd.sh
-          uhd lambda restart-functions ci-$SHORT_SHA
-          uhd lambda restart-functions ci-$SHORT_SHA-a
+          uhd ecs restart-services
+          uhd lambda restart-functions
         shell: zsh {0}
 
   terraform_destroy:
     name: Terraform destroy
     runs-on: ubuntu-latest
-    if: ${{ always() }}
     needs: ["restart_services"]
+    if: always()
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
 
       - name: Configure AWS credentials
-        uses: ./.github/actions/configure-aws-credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
+          role-to-assume: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
           aws-region: ${{ env.AWS_REGION }}
-          tools-account-role: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
 
       - uses: ./.github/actions/setup-terraform
       - uses: ./.github/actions/setup-zsh
-      - uses: ./.github/actions/short-sha
 
-      - name: Terraform destroy for public & auth
+      - name: Destroy Terraform resources
         run: |
           source uhd.sh
-          uhd terraform init:layer 20-app
-          uhd terraform destroy:layer 20-app ci-$SHORT_SHA
-          uhd terraform destroy:layer 20-app ci-$SHORT_SHA-a
-        shell: zsh {0}
-
-  clean_up_remaining_resources:
-    name: Clean up remaining resources
-    runs-on: ubuntu-latest
-    if: ${{ always() }}
-    needs: ["terraform_destroy"]
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Configure AWS credentials
-        uses: ./.github/actions/configure-aws-credentials
-        with:
-          aws-region: ${{ env.AWS_REGION }}
-          tools-account-role: ${{ secrets.UHD_TERRAFORM_IAM_ROLE }}
-
-      - uses: ./.github/actions/setup-zsh
-      - uses: ./.github/actions/short-sha
-
-      - name: Delete secrets for public & auth
-        run: |
-          source uhd.sh
-          uhd secrets delete-all-secrets ci-$SHORT_SHA
-          uhd secrets delete-all-secrets ci-$SHORT_SHA-a
+          uhd terraform destroy:layer 20-app $PUBLIC_ENV
+          uhd terraform destroy:layer 20-app $AUTH_ENV
         shell: zsh {0}
