CDD-2442 Modify path for checkout

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -21,8 +21,16 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
+
+      - name: Debug Checkout Path
+        run: |
+          echo "Current Directory: $(pwd)"
+          ls -la
+          ls -la .github || echo ".github directory is missing!"
+          ls -la .github/actions || echo ".github/actions is missing!"
+          ls -la .github/actions/mask-secrets || echo "mask-secrets action is missing!"
 
       - name: Debug Repository Files
         run: |
@@ -61,7 +69,7 @@ jobs:
         with:
           ref: ${{ github.base_ref }}
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - name: Mask Secrets
@@ -159,7 +167,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - uses: ./.github/actions/setup-zsh
@@ -215,7 +223,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - name: Mask Secrets
@@ -248,7 +256,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - name: Mask Secrets
@@ -300,7 +308,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - name: Mask Secrets
@@ -448,7 +456,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - uses: actions/setup-python@v5
@@ -599,7 +607,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - name: Configure AWS credentials (${{ matrix.environment }})
@@ -631,7 +639,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - name: Configure AWS credentials (${{ matrix.environment }})
@@ -689,7 +697,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - uses: actions/setup-python@v5
@@ -783,7 +791,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: data-dashboard-infra
+          path: "."
           sparse-checkout: false
 
       - name: Configure AWS credentials for tools account
